### GET health
GET http://localhost:8080/health

### GET transactions
GET http://localhost:8080/lime/all

### GET transaction by hash
GET http://localhost:8080/lime/eth?transactionHashes=0x8cb7aa73dc5914082abc11835b1dd48dd49757ceb266d92fc2ae8bda6ec94820
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkzNTE0MjEsInVzZXJuYW1lIjoiYm9iIn0.fL4DN8ZviZrMEXaUwJrfTlmSbmvlyk9Eus5d4KcA4N0

### POST register user
POST http://localhost:8080/lime/register
Content-Type: application/json

{
    "username": "carol",
    "password": "carol"
}

### POST authenticate user
POST http://localhost:8080/lime/authenticate
Content-Type: application/json

{
    "username": "bob",
    "password": "bob"
}

### GET my user
GET http://localhost:8080/lime/my
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkzNTAwMzUsInVzZXJuYW1lIjoiYm9iIn0.GhwLqcnskv6PlqSfHBOcCdRTBz88Fr9yVaT1RMvn-do
