### GET health
GET http://localhost:8080/health

### GET transactions
GET http://localhost:8080/lime/all

### GET transaction by hash
GET http://localhost:8080/lime/eth?transactionHashes=0x7a3fc6c42d63050e957a228926bf3d7bf56daaaf98e61f1e926deef0c264c3dc
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkzNjI3MTMsInVzZXJuYW1lIjoiYm9iIn0.KigETcW85onIIMP-tCmNMiXO_NkWjqi2bQNoo5uB-6c

### POST register user
POST http://localhost:8080/lime/register
Content-Type: application/json

{
    "username": "carol",
    "password": "carol"
}

### POST authenticate user
POST http://localhost:8080/lime/authenticate
Content-Type: application/json

{
    "username": "bob",
    "password": "bob"
}

### GET my user
GET http://localhost:8080/lime/my
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzkzNTAwMzUsInVzZXJuYW1lIjoiYm9iIn0.GhwLqcnskv6PlqSfHBOcCdRTBz88Fr9yVaT1RMvn-do
